
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module rtl_top_test(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);

//=======================================================
//  REG/WIRE declarations
//=======================================================
wire sys_clk, rst_n;

assign sys_clk = CLOCK_50;
assign rst_n = KEY[0];


//=======================================================
//  Structural coding
//=======================================================
rtl_top #(
	.BOARD_NUM	   (1)
) u_rtl_top (
    .sys_clk       (sys_clk),
    .rst_n         (rst_n),

    .KEY           (KEY),
    .SW            (SW),
    .PS2_CLK       (PS2_CLK),
    .PS2_CLK2      (PS2_CLK2),
    .PS2_DAT       (PS2_DAT),
    .PS2_DAT2      (PS2_DAT2),
    .LEDR          (LEDR),

    // VGA
    .VGA_BLANK_N   (VGA_BLANK_N),
    .VGA_B         (VGA_B),
    .VGA_CLK       (VGA_CLK),
    .VGA_G         (VGA_G),
    .VGA_HS        (VGA_HS),
    .VGA_R         (VGA_R),
    .VGA_SYNC_N    (VGA_SYNC_N),
    .VGA_VS        (VGA_VS),

	.GPIO		   (GPIO),

	.HEX0		   (HEX0),
	.HEX1		   (HEX1),
	.HEX2		   (HEX2),
	.HEX3		   (HEX3),
	.HEX4		   (HEX4),
	.HEX5		   (HEX5)
);

endmodule
