
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module ppu_demo(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);

wire rst_n;
wire vga_clk;

vga_pll pll (.refclk(CLOCK_50), .rst(1'b0), .outclk_0(vga_clk));

PPU ppu_mod (
		.vga_clk(vga_clk),
		.VGA_CLK(VGA_CLK),
		.rst_n(rst_n),
		.r(VGA_R), 
		.g(VGA_G), 
		.b(VGA_B), 
		.VGA_BLANK_N(VGA_BLANK_N),
		.VGA_HS(VGA_HS),
		.VGA_SYNC_N(VGA_SYNC_N),
		.VGA_VS(VGA_VS));

assign rst_n = KEY[0];

endmodule
