
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module keyboard_demo(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);

// default everything to 0 for now;
assign VGA_BLANK_N = 0;
assign VGA_B = 0;
assign VGA_CLK = 0;
assign VGA_G = 0;
assign VGA_HS = 0;
assign VGA_R = 0;
assign VGA_SYNC_N = 0;
assign VGA_VS = 0;

wire [1:0] dir;
wire fire, done;

keyboard ps2_driver (.sys_clk(CLOCK_50), .rst_n(KEY[0]), .ps_clk(PS2_CLK), .ps_data(PS2_DAT), .direction(dir), .fire(fire), .done(done));

assign LEDR = {dir, fire, done, 6'h00};
endmodule
